const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUh2T3hDVXdyOHE0RU9BT1FTZEJHVGxNT2EwRXVzR0JWNnVNZS9NeTdHRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSC9xWFFVWVZzT2NPNHk5YjJMN2YwN3owNURUdDhTRER5NUNneHZPVHRBcz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQmE4UTM3K3F3Q0wrbk90eExFazM3TG0zdHlvRkN6bC9CeG14U1RNcFVnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwOGZsZWUwR3d6eEd5amFSem1qNHVWNVMzUlZXMTdmbFpGdWhFSStmZmc4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFEb1VjZ2pIbnVCZTFtUjVtc1R4Ymtzb0N4V1E4QmNuN0lrUFM2UWw0RjQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjExeTN2aTMxVTNtanJSUm5RMlV4YkdpSHhTaGxQNGczcUxXVDMxQk9xRHc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUZBcmZOSUFOaUF5OWgwbEpoaXpSTWVCRU5RLyszNUJacllzN0tSclRscz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM3VzZmpTSmZyZlZMMVVsczI5LzA0NzJRMFlOUEpCRWxJd2hZeVRYVnBRTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InF2WStOQkZYQTlPYlRlb0NjZ1d1OTNQK05JMHdSTFF0QStlaGpLN2JvTkFCNk5Uejk4QXlzcEo1cjVrQkh4OWZGZThSaW5naU9pLzYrSDUxeEVTRmh3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NiwiYWR2U2VjcmV0S2V5IjoiWmREWDBvRk5NYzNTd081TzU2Ty80UXAzcjhDNHo1KzREdXJkWGhZZ1dnTT0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiem9Ra2JqLUJSZUtWT0h5Y3BhczBhZyIsInBob25lSWQiOiJmMjUzZDRiZS04NDYyLTRkMTMtOGRjYS0wNTZlNDlkM2YzYWQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEppM0xuU3dERkNrNExIbEc3MGZ0TnpGU0NnPSJ9LCJyZWdpc3RlcmVkIjpmYWxzZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJaQmJxdHhSNzRlT0lIUklhV3pyZXdjT3oreXc9In0sInJlZ2lzdHJhdGlvbiI6e30sImFjY291bnQiOnsiZGV0YWlscyI6IkNLbmgxWU1ERU42NjZyc0dHQkVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ1dU1VVk1pcGRia1JQaGFGaUZQOEZSZTM1SE1udXUvaytqQ2JlUjU4MEI4PSIsImFjY291bnRTaWduYXR1cmUiOiJwTkZZY1JOR2p1dXpIVndYamZkK0tUOHNHZk82dXBtcnVLZWQ4cGNXZXV1Y2JYVWU0d2NYZWZDSU1KdWRIOFo3Mk1PYmgrTjl5LzY0Z2xwZjZ2YXhBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiaGtFV2V2dlpmZmJwTHc5Z2pQZm5EVGhxY1FJMFNtSjVLK21TUnRsSnNrY2dZalV0UzR1dFVlbHMzT215MFdrdnJiWjZXcHArSVJURUNiRTd2YVhqakE9PSJ9LCJtZSI6eyJpZCI6IjIzNDkxNTUxNzczMTU6MjdAcy53aGF0c2FwcC5uZXQifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0OTE1NTE3NzMxNToyN0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJicmpGRlRJcVhXNUVUNFdoWWhUL0JVWHQrUnpKN3J2NVBvd20za2VmTkFmIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM2MDg4OTM5fQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
